# Generated by Django 3.1.5 on 2021-01-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=150, verbose_name='Адрес')),
                ('workinghours', models.CharField(max_length=50, verbose_name='Время работы')),
                ('minimaltimeforpayment', models.CharField(max_length=50, verbose_name='Минимальное время для оплаты')),
                ('price', models.FloatField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Парковка',
                'verbose_name_plural': 'Парковки',
            },
        ),
    ]
