# Generated by Django 3.1.5 on 2021-01-29 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20210120_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='paidparking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carnumber', models.CharField(max_length=150, verbose_name='Номер автомобиля')),
                ('amountoftime', models.IntegerField(verbose_name='Количество времени')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('telephone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=150, verbose_name='Электронный адрес')),
                ('adress', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.parking', verbose_name='Адрес парковки')),
            ],
            options={
                'verbose_name': 'Оплаченная парковка',
                'verbose_name_plural': 'Оплаченные парковки',
            },
        ),
    ]
