# Generated by Django 3.1.5 on 2021-01-29 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_paidparking'),
    ]

    operations = [
        migrations.CreateModel(
            name='paidseasontickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carnumber', models.CharField(max_length=150, verbose_name='Номер автомобиля')),
                ('numberofdays', models.CharField(max_length=150, verbose_name='Количество дней')),
                ('time', models.IntegerField(verbose_name='Режим работы абонемента')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('telephone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=150, verbose_name='Электронный адрес')),
                ('nametickets', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.tickets', verbose_name='Наименование абонемента')),
            ],
            options={
                'verbose_name': 'Оплаченный абонемент',
                'verbose_name_plural': 'Оплаченные абонементы',
            },
        ),
    ]
