# Generated by Django 3.1.5 on 2021-01-29 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_paidseasontickets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paidparking',
            name='email',
        ),
    ]
