# Generated by Django 3.1.5 on 2021-01-29 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_remove_paidparking_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paidseasontickets',
            name='email',
        ),
        migrations.RemoveField(
            model_name='paidseasontickets',
            name='numberofdays',
        ),
        migrations.RemoveField(
            model_name='paidseasontickets',
            name='time',
        ),
    ]
