# Generated by Django 3.1.5 on 2021-02-01 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20210129_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
    ]
