# Generated by Django 3.1.5 on 2021-02-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_auto_20210201_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
    ]
