# Generated by Django 3.1.5 on 2021-02-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_auto_20210205_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paidparking',
            name='datetimepaidparking',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время оплаты'),
        ),
        migrations.AlterField(
            model_name='paidseasontickets',
            name='datetimepaidtickets',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время оплаты'),
        ),
    ]
