# Generated by Django 3.1.5 on 2021-03-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_auto_20210205_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='paidparking',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Электронный адрес'),
        ),
    ]
