# Generated by Django 3.1.5 on 2021-03-11 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_paidparking_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='paidseasontickets',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Электронный адрес'),
        ),
    ]
