# Generated by Django 3.1.5 on 2021-03-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0017_auto_20210311_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='paidparking',
            name='expirationdate',
            field=models.DateTimeField(null=True, verbose_name='Окончание срока действия'),
        ),
        migrations.AddField(
            model_name='paidparking',
            name='startofvalidityperiod',
            field=models.DateTimeField(null=True, verbose_name='Начало срока действия'),
        ),
        migrations.AddField(
            model_name='paidseasontickets',
            name='expirationdate',
            field=models.DateTimeField(null=True, verbose_name='Окончание срока действия'),
        ),
        migrations.AddField(
            model_name='paidseasontickets',
            name='startofvalidityperiod',
            field=models.DateTimeField(null=True, verbose_name='Начало срока действия'),
        ),
    ]
