# Generated by Django 3.1.5 on 2021-03-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0018_auto_20210311_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paidparking',
            name='expirationdate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Окончание срока действия'),
        ),
    ]
