# Generated by Django 3.1.5 on 2021-03-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0019_auto_20210311_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paidseasontickets',
            name='expirationdate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Окончание срока действия'),
        ),
    ]
