# Generated by Django 3.1.5 on 2021-03-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0020_auto_20210315_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paidparking',
            name='startofvalidityperiod',
        ),
        migrations.RemoveField(
            model_name='paidseasontickets',
            name='startofvalidityperiod',
        ),
        migrations.AddField(
            model_name='paidparking',
            name='enddateandtime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Окончание срока действия'),
        ),
        migrations.AddField(
            model_name='paidparking',
            name='expirationtime',
            field=models.TimeField(null=True, verbose_name='Дата начала срока действия'),
        ),
        migrations.AddField(
            model_name='paidseasontickets',
            name='enddateandtime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Окончание срока действия'),
        ),
        migrations.AddField(
            model_name='paidseasontickets',
            name='expirationtime',
            field=models.TimeField(null=True, verbose_name='Дата начала срока действия'),
        ),
        migrations.AlterField(
            model_name='paidparking',
            name='expirationdate',
            field=models.DateField(null=True, verbose_name='Дата начала срока действия'),
        ),
        migrations.AlterField(
            model_name='paidseasontickets',
            name='expirationdate',
            field=models.DateField(null=True, verbose_name='Дата начала срока действия'),
        ),
    ]
