# Generated by Django 3.1.5 on 2021-04-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0021_auto_20210325_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parking',
            name='workinghours',
        ),
        migrations.AddField(
            model_name='parking',
            name='endtime',
            field=models.TimeField(null=True, verbose_name='Время конца работы'),
        ),
        migrations.AddField(
            model_name='parking',
            name='starttime',
            field=models.TimeField(null=True, verbose_name='Время начала работы'),
        ),
        migrations.AlterField(
            model_name='paidparking',
            name='expirationtime',
            field=models.TimeField(null=True, verbose_name='Время начала срока действия'),
        ),
        migrations.AlterField(
            model_name='paidseasontickets',
            name='expirationtime',
            field=models.TimeField(null=True, verbose_name='Время начала срока действия'),
        ),
    ]
