# Generated by Django 3.1.5 on 2021-04-29 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0023_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'Пользователи telegram', 'verbose_name_plural': 'Пользователи telegram'},
        ),
    ]
