# Generated by Django 3.1.5 on 2021-05-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0025_parking_videofromthecamera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='videofromthecamera',
            field=models.CharField(blank=True, max_length=500, verbose_name='Видеоизображение с камеры'),
        ),
    ]
